### PR TITLE
Port to TelepathyGLib

### PR DESCRIPTION
**Pull request by quozl**
Fixes https://github.com/sugarlabs/collabwrapper/issues/1.

Replaces https://github.com/sugarlabs/collabwrapper/pull/14.

@Aniket21mathur, @chimosky, @pro-panda, please review.

### CODE REVIEW

**Comment by Aniket21mathur** [comment]
Thanks. Reviewed.

**Comment by chimosky** [comment]
Reviewed, works as intended. Thanks.

@Aniket21mathur see https://github.com/sugarlabs/collabwrapper/pull/15/files#diff-522d50df40395298c4143ef36ee6a1f6R81

**Comment by Aniket21mathur** [comment]
Thanks for testing @chimosky. By adding a key I meant by adding a key to the toolkit, as per the new way of making a dictionary of Interfaces that we are following. Please see https://github.com/sugarlabs/sugar-toolkit-gtk3/pull/412/commits/d7fe5ae3fb885979bc6e3bd070f7316862b011a6. And sorry for the incomplete explanation.

**Comment by chimosky** [comment]
> Thanks for testing @chimosky. By adding a key I meant by adding a key to the toolkit, as per the new way of making a dictionary of Interfaces that we are following. Please see [sugarlabs/sugar-toolkit-gtk3@d7fe5ae](https://github.com/sugarlabs/sugar-toolkit-gtk3/commit/d7fe5ae3fb885979bc6e3bd070f7316862b011a6). And sorry for the incomplete explanation.

Just checked, it was added https://github.com/sugarlabs/sugar-toolkit-gtk3/blob/d7fe5ae3fb885979bc6e3bd070f7316862b011a6/src/sugar3/presence/activity.py#L38

**Comment by Aniket21mathur** [comment]
Thanks. I was not trying to ask about import of _CHANNEL_INTERFACE_GROUP_, instead asking whether it is added as a key in the text_channel dictionary, yes it gets added, through this https://github.com/sugarlabs/sugar-toolkit-gtk3/pull/412/files#diff-03de8f54944bb6037c70d8ec36f91c15R627. @chimosky please have a look. :smile: 

@quozl , what should we do next?

**Comment by quozl** [comment]
> @quozl Did we added any key for _CHANNEL_INTERFACE_GROUP_ ?, please see https://github.com/sugarlabs/collabwrapper/pull/15/files#diff-522d50df40395298c4143ef36ee6a1f6R815

Sorry, I don't understand your question.  Try again?

**Comment by Aniket21mathur** [comment]
> Sorry, I don't understand your question. Try again?

Had a query, cleared it myself. Though happy to explain again :-).
https://github.com/sugarlabs/collabwrapper/pull/15/files#diff-522d50df40395298c4143ef36ee6a1f6R815
uses _CHANNEL_INTERFACE_GROUP_ as a key to the self._text_chan dictionary. I was not sure whether we defined it in the toolkit or not. But after realised that it gets added through https://github.com/sugarlabs/sugar-toolkit-gtk3/pull/412/files#diff-03de8f54944bb6037c70d8ec36f91c15R627.

Thanks!

**Comment by quozl** [comment]
Ah, I see.  In other words, is a [Channel.Interface.Group](https://telepathy.freedesktop.org/spec/Channel_Interface_Group.html) D-Bus interface created.

**Pull request merged**
