### PR TITLE
Port telepathy static bindings to TelepathyGLib

### PR DESCRIPTION
**Pull request by chimosky**

### CODE REVIEW

**Comment by quozl** [comment]
It is unfortunate that you don't have a way to test; you should work first on that problem, because it affects the quality of your code.

You do have flake8.
```flake8
collabwrapper.py:448:80: E501 line too long (89 > 79 characters)
collabwrapper.py:548:35: F821 undefined name 'TelapthyGLib'
collabwrapper.py:548:80: E501 line too long (80 > 79 characters)
collabwrapper.py:621:17: F821 undefined name 'CHANNEL_TYPE_FILE_TRANSFER'
collabwrapper.py:623:17: F821 undefined name 'CONNECTION_HANDLE_TYPE_CONTACT'
collabwrapper.py:719:80: E501 line too long (85 > 79 characters)
collabwrapper.py:740:29: F821 undefined name 'CHANNEL_INTERFACE'
collabwrapper.py:771:80: E501 line too long (82 > 79 characters)
collabwrapper.py:793:80: E501 line too long (98 > 79 characters)
collabwrapper.py:805:80: E501 line too long (93 > 79 characters)
```

The F821 would cause traceback and failure during run.

**Comment by chimosky** [comment]
[Older versions](https://lintlyci.github.io/Flake8Rules/rules/W504.html) of flake 8 throw this error, but [newer versions](https://www.python.org/dev/peps/pep-0008/#should-a-line-break-before-or-after-a-binary-operator) don't
```
collabwrapper.py:578:17: W503 line break before binary operator
collabwrapper.py:626:17: W503 line break before binary operator
collabwrapper.py:628:17: W503 line break before binary operator
collabwrapper.py:630:17: W503 line break before binary operator
collabwrapper.py:632:17: W503 line break before binary operator
collabwrapper.py:634:17: W503 line break before binary operator
collabwrapper.py:662:17: W503 line break before binary operator
collabwrapper.py:840:15: W503 line break before binary operator
```

**Comment by chimosky** [comment]
[Older versions](https://lintlyci.github.io/Flake8Rules/rules/W504.html) of flake 8 throw this error, but [newer versions](https://www.python.org/dev/peps/pep-0008/#should-a-line-break-before-or-after-a-binary-operator) don't
```
collabwrapper.py:578:17: W503 line break before binary operator
collabwrapper.py:626:17: W503 line break before binary operator
collabwrapper.py:628:17: W503 line break before binary operator
collabwrapper.py:630:17: W503 line break before binary operator
collabwrapper.py:632:17: W503 line break before binary operator
collabwrapper.py:634:17: W503 line break before binary operator
collabwrapper.py:662:17: W503 line break before binary operator
collabwrapper.py:840:15: W503 line break before binary operator
```

**Comment by quozl** [comment]
I've tested on Fedora 18, and it doesn't work.  There's a traceback when a message is received, which cancels further processing of the message.  Please test before commit, thanks.

**Comment by pro-panda** [comment]
Stale

**Comment by Aniket21mathur** [comment]
> I've tested on Fedora 18, and it doesn't work. There's a traceback when a message is received, which cancels further processing of the message. Please test before commit, thanks.

May I know which activity, you used to test it. Thanks. I tried with collabedit and collabwrapper test activity but it seems to me that collaboration is broken for these. Thanks!

**Comment by quozl** [comment]
I've no idea, sorry.  It was too long ago; 103 days.  I've nothing about the test in my day notes for that date.  If it helps, I would have tested with Sugar 0.112, as the release of 0.113 was on 13th March.  Also, as the test was on Fedora 18, Sugar 0.112 is the latest I've packaged, and I've no plans to package beyond 0.112 for Fedora 18 as 0.113 requires later versions of some dependencies.

**Comment by chimosky** [comment]
> > I've tested on Fedora 18, and it doesn't work. There's a traceback when a message is received, which cancels further processing of the message. Please test before commit, thanks.
> 
> May I know which activity you used to test it. Thanks. I tried with collabedit and collabwrapper test activity but it seems to me that collaboration is broken for these. Thanks!

I tested with the collabwrapper test activity.

**Comment by Aniket21mathur** [comment]
Thanks @chimosky, I tried with it but the test activity itself resulted in a broken collaboration.

**Comment by quozl** [comment]
> Thanks @chimosky, I tried with it but the test activity itself resulted in a broken collaboration.

Not enough information.  Please give more information.  I'm alarmed that the test activity itself might have stopped working, so I've tested it again.  The test activity worked for me just now, using the following source code and virtual machine configuration;
* module _sugar_ version 0.112 from package,
* module _sugar-toolkit-gtk3_ version https://github.com/sugarlabs/sugar-toolkit-gtk3/commit/12a899f3740f2d82ea16c2ec28b24198f76fd47a (the head of _master_ branch),
* module _collabwrapper_ branch _test_ version https://github.com/sugarlabs/collabwrapper/commit/d0bdb328eed73357a299d047eaf68049bb58e45f (the head of _test_ branch, also CollabWrapperTest-1.xo md5sum b25aaaf00404fc4d412cff47ec9f59be),
* two virtual machines running Ubuntu 19.04 with a [bridged network configuration](https://jamielinux.com/docs/libvirt-networking-handbook/bridged-network.html).

Working for me is;
* buddy icon appears in network neighbourhood,
* when shared, the activity icon appears in network neighbourhood,
* when joined, the activity shows "buddy-joined",
* messages can be sent between the activities,
* the <kbd>ctrl</kbd>+<kbd>p</kbd> (ping) showed latency below 100ms on both activities.

Please confirm that the test activity runs for you _before_ porting _collabwrapper_ or _sugar-toolkit-gtk3_ modules?

**Comment by Aniket21mathur** [comment]
I used the following source code and configuration-

- module sugar version 0.112 from package.

- module sugar toolkit version 0.112 from package.

- module collabwrapper branch:test https://github.com/sugarlabs/collabwrapper/commit/d0bdb328eed73357a299d047eaf68049bb58e45f (the head of test branch).

- two sugar instances using rdesktop (Ubuntu 18.04).

I observed the following-

- buddy icon appears in network neighbourhood view of both the instances.

- when shared from first instances the activity icon appears in neighbourhood view of that instance
only and not in the neighbourhood view of the second instance.

- Nothing in the logs.

I observe that our configurations differ, I made a virtual machine running Ubuntu 19.04, and will test using that. Thanks!

**Comment by quozl** [comment]
Okay, good data; some questions;

* does the buddy icon for the other instance appear in the neighbourhood view of the instance?  for a two instance test, you should see one buddy icon in the centre, and one randomly placed away from centre,
* can you ping the IP address of one virtual machine from the other?  this will test connectivity across the bridge, necessary for any collaboration to occur,
* where does the activity icon appear in neighbourhood view?  it would normally be randomly placed, not intentionally adjacent to the centre or any other buddy.
* does the buddy icon in the neighbourhood view of the other instance change position at the time the activity begins to be shared?

**Comment by Aniket21mathur** [comment]
> * does the buddy icon for the other instance appear in the neighbourhood view of the instance?  for a two instance test, you should see one buddy icon in the centre, and one randomly placed away from centre

Yes, it appears as you described.

> * can you ping the IP address of one virtual machine from the other?  this will test connectivity across the bridge, necessary for any collaboration to occur

I must add that both the virtual machine are running on localhost(127.0.0.1), as I run
`rdesktop -u guest -p guest 127.0.0.1` &
`rdesktop -u guest1 -p guest1 127.0.0.1`
to start the two machines. When I do Ifconfig in the terminal activity the output for both the machines is same.

> * where does the activity icon appear in neighbourhood view?  it would normally be randomly placed, not intentionally adjacent to the centre or any other buddy.

Yes it appears randomly in the neighbourhood of the instance from which the activity is shared and do not occur in the neighbourhood of the other instance.

> * does the buddy icon in the neighbourhood view of the other instance change position at the time the activity begins to be shared?

No, it does not appear to change position, although I am interested to know how this point will affect collaboration.

I must also add that I am able to collaborate with activities like chat, calculate and Maze.
Thanks!

**Comment by quozl** [comment]
> I must add that both the virtual machine are running on localhost(127.0.0.1), as I run
> `rdesktop -u guest -p guest 127.0.0.1` &
> `rdesktop -u guest1 -p guest1 127.0.0.1`
> to start the two machines. When I do Ifconfig in the terminal activity the output for both the machines is same.

Oh!  That's not virtual machines.  That's different login sessions on the same machine.  I don't test that way.  I use separate KVM virtual machines or separate laptops.  I wonder if it will work.  In your test, each user will have the same _buddy.props.ip4_address_.  Please check the value of _buddy.props.nick_ and make sure it is unique.  It can be set using <kbd>alt</kbd>+<kbd>shift</kbd>+<kbd>m</kbd> _About Me_.  Please check that the digital keys are different; `.sugar/default/owner.key{,.pub}`.

> No, it does not appear to change position, although I am interested to know how this point will affect collaboration.

In some of my tests, when an activity is shared by a user, other users see the buddy icon disappear and reappear somewhere else on the neighbourhood view.  Placing the mouse below the buddy icon (Y + cell size) shows an offer to join.  The icon was not rendered.  Causes have been white on white icon, or perhaps activity not installed.

> I must also add that I am able to collaborate with activities like chat, calculate and Maze.

That's good to know.  What do you think CollabWrapper is failing to do in the same way that Chat, Calculate and Maze successfully do?

**Comment by Aniket21mathur** [comment]
> Please check that the digital keys are different; `.sugar/default/owner.key{,.pub}`

Yes they are different.

> Please check the value of _buddy.props.nick_ and make sure it is unique

Yes they are unique, `guest` and `guest1`.

>  In your test, each user will have the same _buddy.props.ip4_address_.

Yes, I accept that they have the same ip4_address.

> That's good to know. What do you think CollabWrapper is failing to do in the same way that Chat, Calculate and Maze successfully do?

One think I never paid attention to is that on sharing Chat, Calculate and Maze the activity icon do not appear in the neighbourhood of the other instance, same as for Collabwrapper, but on hovering the mouse on the buddy icon of the other instance in the neihbourhood view of the first instance I got an option to invite to these activities. So invitation was the only way to collaborate, there was no join option for the other instance. Different sessions on the same machine having same ip4_address might be causing it.   

> I don't test that way. I use separate KVM virtual machines or separate laptops

Using different laptops is not possible for me right now, though I can try using two separate Oracle virtual machines. I accept that I do have hardware limitations.

Thanks!

**Comment by quozl** [comment]
> One thing I never paid attention to is that on sharing Chat, Calculate and Maze the activity icon do not appear in the neighbourhood of the other instance, same as for CollabWrapper, but on hovering the mouse on the buddy icon of the other instance in the neighbourhood view of the first instance I got an option to invite to these activities. So invitation was the only way to collaborate, there was no join option for the other instance. Different sessions on the same machine having the same ip4_address might be causing it.

I agree, it may be the same IPv4 address causing this, because of how Salut uses Clique and mDNS.  I can't remember testing collaboration using multiple logins on the same host.  It is interesting that invitation still works, even if sharing and joining does not.

**Pull request closed without merging**
